<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { BarChart3, Bell, CalendarDays, ChevronDown, FolderKanban, LayoutDashboard, LogOut, Menu, Settings, ShieldCheck, X } from '@lucide/vue'
import { api } from '../lib/api'; import { useSessionStore } from '../stores/session'
const session = useSessionStore(); const route = useRoute(); const router = useRouter(); const mobileOpen = ref(false); const notificationsOpen = ref(false); const notifications = ref<Array<{id:string;title:string;body:string;readAt:number|null;createdAt:number}>>([])
const nav = [{ to: '/overview', label: '總覽', icon: LayoutDashboard }, { to: '/campaigns', label: '內容企劃', icon: FolderKanban }, { to: '/reviews', label: '審核中心', icon: ShieldCheck }, { to: '/calendar', label: '內容日曆', icon: CalendarDays }, { to: '/analytics', label: '成效分析', icon: BarChart3 }, { to: '/settings', label: '設定', icon: Settings }]
const title = computed(() => nav.find((item) => route.path.startsWith(item.to))?.label ?? 'Social Studio')
async function changeWorkspace(event: Event) { await session.selectWorkspace((event.target as HTMLSelectElement).value); router.push('/overview') }
function changeBrand(event: Event) { session.selectBrand((event.target as HTMLSelectElement).value); window.dispatchEvent(new Event('brand-change')) }
async function showNotifications() { notificationsOpen.value = !notificationsOpen.value; if (notificationsOpen.value) notifications.value = await api.notifications() }
async function logout() { await session.logout(); router.push('/login') }
</script>
<template><div class="studio-shell"><aside class="sidebar" :class="{ open: mobileOpen }"><div class="sidebar-brand"><span>S</span><strong>Social Studio</strong><button class="mobile-close" @click="mobileOpen=false"><X /></button></div><div class="workspace-select"><small>工作空間</small><label><select :value="session.workspaceId" @change="changeWorkspace"><option v-for="item in session.workspaces" :key="item.id" :value="item.id">{{ item.name }}</option></select><ChevronDown :size="14" /></label></div><nav><RouterLink v-for="item in nav" :key="item.to" :to="item.to" @click="mobileOpen=false"><component :is="item.icon" :size="18" />{{ item.label }}</RouterLink></nav><div class="sidebar-user"><span>{{ session.user?.displayName.slice(0,1) }}</span><div><strong>{{ session.user?.displayName }}</strong><small>{{ session.workspace?.role }}</small></div><button aria-label="登出" @click="logout"><LogOut :size="16" /></button></div></aside><div v-if="mobileOpen" class="mobile-scrim" @click="mobileOpen=false"/><section class="workspace-area"><header class="topbar"><button class="mobile-menu" @click="mobileOpen=true"><Menu /></button><div><p>{{ session.brand?.name }}</p><h1>{{ title }}</h1></div><div class="topbar-actions"><label class="brand-select">品牌<select :value="session.brandId" @change="changeBrand"><option v-for="brand in session.brands" :key="brand.id" :value="brand.id">{{ brand.name }}</option></select><ChevronDown :size="14" /></label><button class="notification-button" aria-label="通知" @click="showNotifications"><Bell :size="19" /><i v-if="notifications.some(n=>!n.readAt)" /></button></div><div v-if="notificationsOpen" class="notification-popover"><div><strong>通知</strong><button @click="notificationsOpen=false"><X :size="16" /></button></div><p v-if="!notifications.length" class="muted">目前沒有通知</p><article v-for="item in notifications" :key="item.id"><strong>{{ item.title }}</strong><p>{{ item.body }}</p><small>{{ new Date(item.createdAt).toLocaleString('zh-TW') }}</small></article></div></header><main class="page-content"><RouterView :key="`${session.workspaceId}:${session.brandId}`" /></main></section></div></template>
