<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { CalendarDays, ChevronLeft, ChevronRight, List, Rows3 } from '@lucide/vue'; import { api, type CalendarItem } from '../lib/api'; import { useSessionStore } from '../stores/session'
const session=useSessionStore();const router=useRouter();const items=ref<CalendarItem[]>([]);const mode=ref<'month'|'week'|'list'>('month');const cursor=ref(new Date());const error=ref('')
async function load(){items.value=await api.calendar(session.brandId)}
const days=computed(()=>{const base=cursor.value;const first=mode.value==='week'?new Date(base.getFullYear(),base.getMonth(),base.getDate()-base.getDay()):new Date(base.getFullYear(),base.getMonth(),1);const start=mode.value==='week'?first:new Date(first.getFullYear(),first.getMonth(),1-first.getDay());return Array.from({length:mode.value==='week'?7:42},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i))})
const sorted=computed(()=>[...items.value].sort((a,b)=>a.scheduledAt-b.scheduledAt));function sameDay(value:number,date:Date){const d=new Date(value);return d.getFullYear()===date.getFullYear()&&d.getMonth()===date.getMonth()&&d.getDate()===date.getDate()}
function move(step:number){cursor.value=mode.value==='week'?new Date(cursor.value.getTime()+step*7*86400000):new Date(cursor.value.getFullYear(),cursor.value.getMonth()+step,1)}
async function drop(event:DragEvent,date:Date){const raw=event.dataTransfer?.getData('text/plain');if(!raw)return;const item=items.value.find(i=>i.id===raw);if(!item||!['scheduled','failed'].includes(item.status))return;const original=new Date(item.scheduledAt);const next=new Date(date.getFullYear(),date.getMonth(),date.getDate(),original.getHours(),original.getMinutes()).getTime();try{await api.schedule(item.campaignId,item.postId,item.id,next);await load()}catch(e){error.value=e instanceof Error?e.message:'無法更新排程'}}
function open(item:CalendarItem){router.push(`/campaigns/${item.campaignId}/posts/${item.postId}`)}onMounted(load)
</script>
<template><div class="page-stack"><section class="page-title-row"><div><p class="eyebrow">PUBLISHING SCHEDULE</p><h2>內容日曆</h2><p>以品牌與平台掌握發布節奏，拖曳即可調整日期。</p></div><div class="segmented"><button :class="{active:mode==='month'}" @click="mode='month'">月</button><button :class="{active:mode==='week'}" @click="mode='week'"><Rows3 :size="15"/>週</button><button :class="{active:mode==='list'}" @click="mode='list'"><List :size="15"/>列表</button></div></section><p v-if="error" class="form-error banner">{{error}}</p><section v-if="mode!=='list'" class="calendar-panel panel"><div class="calendar-toolbar"><button @click="move(-1)"><ChevronLeft/></button><h3>{{cursor.toLocaleDateString('zh-TW',{year:'numeric',month:'long'})}}</h3><button @click="move(1)"><ChevronRight/></button><button class="today" @click="cursor=new Date()">今天</button></div><div class="weekday-row"><span v-for="day in ['日','一','二','三','四','五','六']" :key="day">{{day}}</span></div><div class="calendar-grid" :class="mode"><div v-for="day in days" :key="day.toISOString()" class="calendar-cell" :class="{outside:day.getMonth()!==cursor.getMonth(),today:sameDay(Date.now(),day)}" @dragover.prevent @drop="drop($event,day)"><strong>{{day.getDate()}}</strong><button v-for="item in items.filter(i=>sameDay(i.scheduledAt,day))" :key="item.id" draggable="true" :class="item.status" @dragstart="$event.dataTransfer?.setData('text/plain',item.id)" @click="open(item)"><span>{{new Date(item.scheduledAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}}</span><b>{{item.postTitle}}</b><small>{{item.platform}}</small></button></div></div></section><section v-else class="panel"><div class="panel-head"><div><p class="eyebrow">SCHEDULE LIST</p><h3>全部排程</h3></div><span>{{sorted.length}} 則</span></div><div v-if="sorted.length" class="schedule-list"><button v-for="item in sorted" :key="item.id" @click="open(item)"><time>{{new Date(item.scheduledAt).toLocaleDateString('zh-TW',{month:'short',day:'numeric'})}}<small>{{new Date(item.scheduledAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}}</small></time><span><strong>{{item.postTitle}}</strong><small>{{item.campaignName}} · {{item.brandName}}</small></span><i class="platform-badge">{{item.platform}}</i><em class="status-chip">{{item.status}}</em></button></div><div v-else class="empty-block large"><CalendarDays/><h3>目前沒有排程內容</h3></div></section></div></template>
