<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { FolderKanban, Plus, Search, X } from '@lucide/vue'; import { api, type CampaignSummary } from '../lib/api'; import { useSessionStore } from '../stores/session'
const session=useSessionStore(); const router=useRouter(); const items=ref<CampaignSummary[]>([]); const search=ref(''); const createOpen=ref(false); const busy=ref(false); const error=ref(''); const form=reactive({name:'',objective:'',brief:''})
const filtered=computed(()=>items.value.filter(i=>`${i.name} ${i.brief}`.toLowerCase().includes(search.value.toLowerCase())))
async function load(){items.value=await api.campaigns(session.brandId)}
async function create(){busy.value=true;error.value='';try{const item=await api.createCampaign({brandId:session.brandId,name:form.name,objective:form.objective,brief:form.brief});await router.push(`/campaigns/${item.id}`);createOpen.value=false}catch(e){error.value=e instanceof Error?e.message:'建立失敗'}finally{busy.value=false}}
onMounted(load)
</script>
<template><div class="page-stack"><section class="page-title-row"><div><p class="eyebrow">CAMPAIGN PLANNING</p><h2>內容企劃</h2><p>用企劃組織系列貼文、負責人與發布節奏。</p></div><button class="button primary" data-testid="create-campaign" @click="createOpen=true"><Plus :size="17"/>建立企劃</button></section><section class="filter-bar"><label><Search :size="17"/><input v-model="search" placeholder="搜尋企劃名稱或簡介"></label><span>{{filtered.length}} 個企劃</span></section><section v-if="filtered.length" class="campaign-card-grid"><button v-for="item in filtered" :key="item.id" @click="router.push(`/campaigns/${item.id}`)"><div class="campaign-card-top"><span class="list-icon"><FolderKanban/></span><i class="status-chip">{{item.status}}</i></div><h3>{{item.name}}</h3><p>{{item.brief||'尚未填寫企劃簡介'}}</p><div><span>{{item.postCount}} 篇內容</span><span>{{item.reviewCount}} 待審核</span><span>{{item.scheduledCount}} 已排程</span></div><small>更新於 {{new Date(item.updatedAt).toLocaleDateString('zh-TW')}}</small></button></section><section v-else class="panel empty-page"><FolderKanban :size="38"/><h3>開始第一個內容企劃</h3><p>企劃可以包含多篇貼文與各平台版本。</p><button class="button primary" @click="createOpen=true">建立企劃</button></section><div v-if="createOpen" class="modal-backdrop" @mousedown.self="createOpen=false"><form class="modal" @submit.prevent="create"><div class="modal-head"><div><p class="eyebrow">NEW CAMPAIGN</p><h2>建立內容企劃</h2></div><button type="button" @click="createOpen=false"><X/></button></div><label>企劃名稱<input v-model="form.name" required minlength="2" placeholder="例如：秋季品牌內容計畫"></label><label>企劃目標<input v-model="form.objective" placeholder="例如：提升收藏與品牌互動"></label><label>內容簡介<textarea v-model="form.brief" rows="4" placeholder="說明核心訊息、受眾與執行方向"></textarea></label><p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button type="button" class="button secondary" @click="createOpen=false">取消</button><button class="button primary" :disabled="busy">建立企劃</button></div></form></div></div></template>
