<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ArrowLeft, Image, Layers3, Plus, Sparkles, Video, X } from '@lucide/vue'; import { api, type CampaignDetail } from '../lib/api'
const route=useRoute();const router=useRouter();const campaign=ref<CampaignDetail|null>(null);const createOpen=ref(false);const busy=ref(false);const notice=ref('');const error=ref('');const form=reactive({title:'',brief:'',format:'image',platforms:['facebook','instagram','threads'] as string[]})
const platforms=['facebook','instagram','threads','x','tiktok','youtube'];const formats=[{value:'image',label:'單張圖片',icon:Image},{value:'carousel',label:'輪播內容',icon:Layers3},{value:'short_video',label:'短影音',icon:Video}]
async function load(){campaign.value=await api.campaign(String(route.params.campaignId))}
async function ideas(){busy.value=true;try{await api.generateIdeas(String(route.params.campaignId));notice.value='AI 正在建立三篇內容提案';setTimeout(load,1200)}catch(e){error.value=e instanceof Error?e.message:'無法產生提案'}finally{busy.value=false}}
async function create(){busy.value=true;error.value='';try{const item=await api.createPost(String(route.params.campaignId),form);await router.push(`/campaigns/${route.params.campaignId}/posts/${item.id}`);createOpen.value=false}catch(e){error.value=e instanceof Error?e.message:'建立失敗'}finally{busy.value=false}}
function togglePlatform(platform:string){form.platforms=form.platforms.includes(platform)?form.platforms.filter(p=>p!==platform):[...form.platforms,platform];if(form.format!=='short_video')form.platforms=form.platforms.filter(p=>p!=='youtube')}
onMounted(load)
</script>
<template><div v-if="campaign" class="page-stack"><button class="back-link" @click="router.push('/campaigns')"><ArrowLeft :size="16"/>返回企劃</button><section class="campaign-hero"><div><span class="status-chip">{{campaign.status}}</span><h2>{{campaign.name}}</h2><p>{{campaign.brief||'尚未填寫企劃簡介'}}</p><div class="campaign-meta"><span>{{campaign.brandName}}</span><span>{{campaign.posts.length}} 篇內容</span><span>{{campaign.objective||'未設定企劃目標'}}</span></div></div><div><button class="button secondary" :disabled="busy" @click="ideas"><Sparkles :size="17"/>AI 內容提案</button><button class="button primary" @click="createOpen=true"><Plus :size="17"/>新增貼文</button></div></section><p v-if="notice" class="notice">{{notice}}</p><section class="panel"><div class="panel-head"><div><p class="eyebrow">CONTENT BOARD</p><h3>企劃內容</h3></div><span>{{campaign.posts.length}} 篇</span></div><div v-if="campaign.posts.length" class="post-board"><button v-for="post in campaign.posts" :key="post.id" @click="router.push(`/campaigns/${campaign.id}/posts/${post.id}`)"><span class="format-icon"><Video v-if="post.format==='short_video'"/><Layers3 v-else-if="post.format==='carousel'"/><Image v-else/></span><div><strong>{{post.title}}</strong><p>{{post.brief||'尚未填寫貼文簡介'}}</p><small>{{post.variantCount}} 個平台 · {{post.assigneeName||'未指派'}}</small></div><i class="status-chip" :class="post.status">{{post.status}}</i></button></div><div v-else class="empty-block large"><Layers3/><h3>企劃還沒有內容</h3><p>使用 AI 產生提案，或自行建立第一篇貼文。</p></div></section><div v-if="createOpen" class="modal-backdrop" @mousedown.self="createOpen=false"><form class="modal large" @submit.prevent="create"><div class="modal-head"><div><p class="eyebrow">NEW POST</p><h2>建立企劃貼文</h2></div><button type="button" @click="createOpen=false"><X/></button></div><label>貼文主題<input v-model="form.title" required minlength="2"></label><label>內容簡介<textarea v-model="form.brief" rows="3"></textarea></label><fieldset><legend>內容格式</legend><div class="choice-grid"><label v-for="item in formats" :key="item.value" :class="{selected:form.format===item.value}"><input v-model="form.format" type="radio" :value="item.value" @change="form.format!=='short_video'&&(form.platforms=form.platforms.filter(p=>p!=='youtube'))"><component :is="item.icon"/><strong>{{item.label}}</strong></label></div></fieldset><fieldset><legend>發布平台</legend><div class="platform-choices"><button v-for="platform in platforms" :key="platform" type="button" :disabled="platform==='youtube'&&form.format!=='short_video'" :class="{selected:form.platforms.includes(platform)}" @click="togglePlatform(platform)">{{platform}}</button></div></fieldset><p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button type="button" class="button secondary" @click="createOpen=false">取消</button><button class="button primary" :disabled="busy||!form.platforms.length">建立貼文</button></div></form></div></div></template>
